import { readFileSync } from "node:fs";
import path from "node:path";
import semver from "semver";

export const IOS_VERSION_FILE = "apps/ios/version.json";
export const IOS_CHANGELOG_FILE = "apps/ios/CHANGELOG.md";
export const IOS_VERSION_XCCONFIG_FILE = "apps/ios/Config/Version.xcconfig";
export const IOS_RELEASE_NOTES_FILE = "apps/ios/fastlane/metadata/en-US/release_notes.txt";

export type IosVersionManifest = {
  version: string;
};

export type ResolvedIosVersion = {
  canonicalVersion: string;
  marketingVersion: string;
  buildVersion: string;
  isPrerelease: boolean;
  prereleaseChannel: string | null;
  prereleaseNumber: number | null;
  versionFilePath: string;
  changelogPath: string;
  versionXcconfigPath: string;
  releaseNotesPath: string;
};

function normalizeCanonicalVersion(rawVersion: string): string {
  const trimmed = rawVersion.trim();
  if (!trimmed) {
    throw new Error(`Missing iOS version in ${IOS_VERSION_FILE}.`);
  }

  const parsed = semver.parse(trimmed);
  if (!parsed) {
    throw new Error(
      `Invalid iOS version '${rawVersion}'. Expected semantic versioning like 1.2.3 or 1.2.3-beta.1.`,
    );
  }

  if (parsed.build.length > 0) {
    throw new Error(
      `Invalid iOS version '${rawVersion}'. Build metadata (+suffix) is not supported for Apple bundle versions.`,
    );
  }

  if (parsed.prerelease.length === 0) {
    return parsed.format();
  }

  const [channel, number] = parsed.prerelease;
  if (channel !== "beta" || typeof number !== "number" || parsed.prerelease.length !== 2) {
    throw new Error(
      `Invalid iOS prerelease '${rawVersion}'. Supported prerelease format is x.y.z-beta.N.`,
    );
  }

  return parsed.format();
}

export function resolveIosVersion(rootDir = path.resolve(".")): ResolvedIosVersion {
  const versionFilePath = path.join(rootDir, IOS_VERSION_FILE);
  const changelogPath = path.join(rootDir, IOS_CHANGELOG_FILE);
  const versionXcconfigPath = path.join(rootDir, IOS_VERSION_XCCONFIG_FILE);
  const releaseNotesPath = path.join(rootDir, IOS_RELEASE_NOTES_FILE);
  const manifest = JSON.parse(readFileSync(versionFilePath, "utf8")) as IosVersionManifest;
  const canonicalVersion = normalizeCanonicalVersion(manifest.version ?? "");
  const parsed = semver.parse(canonicalVersion);
  if (!parsed) {
    throw new Error(`Unable to parse normalized iOS version '${canonicalVersion}'.`);
  }

  const prereleaseChannel =
    parsed.prerelease.length > 0 && typeof parsed.prerelease[0] === "string"
      ? parsed.prerelease[0]
      : null;
  const prereleaseNumber =
    parsed.prerelease.length > 1 && typeof parsed.prerelease[1] === "number"
      ? parsed.prerelease[1]
      : null;

  return {
    canonicalVersion,
    marketingVersion: `${parsed.major}.${parsed.minor}.${parsed.patch}`,
    buildVersion: "1",
    isPrerelease: parsed.prerelease.length > 0,
    prereleaseChannel,
    prereleaseNumber,
    versionFilePath,
    changelogPath,
    versionXcconfigPath,
    releaseNotesPath,
  };
}

export function renderIosVersionXcconfig(version: ResolvedIosVersion): string {
  return `// Shared iOS version defaults.\n// Source of truth: apps/ios/version.json\n// Generated by scripts/ios-sync-versioning.ts.\n\nOPENCLAW_IOS_VERSION = ${version.canonicalVersion}\nOPENCLAW_MARKETING_VERSION = ${version.marketingVersion}\nOPENCLAW_BUILD_VERSION = ${version.buildVersion}\n\n#include? "../build/Version.xcconfig"\n`;
}

function matchChangelogHeading(line: string, heading: string): boolean {
  const normalized = line.trim();
  return normalized === `## ${heading}` || normalized.startsWith(`## ${heading} - `);
}

export function extractChangelogSection(content: string, heading: string): string | null {
  const lines = content.split(/\r?\n/);
  const startIndex = lines.findIndex((line) => matchChangelogHeading(line, heading));
  if (startIndex === -1) {
    return null;
  }

  let endIndex = lines.length;
  for (let index = startIndex + 1; index < lines.length; index += 1) {
    if (lines[index]?.startsWith("## ")) {
      endIndex = index;
      break;
    }
  }

  const body = lines
    .slice(startIndex + 1, endIndex)
    .join("\n")
    .trim();
  return body || null;
}

export function renderIosReleaseNotes(
  version: ResolvedIosVersion,
  changelogContent: string,
): string {
  const candidateHeadings = [version.canonicalVersion];
  if (!candidateHeadings.includes(version.marketingVersion)) {
    candidateHeadings.push(version.marketingVersion);
  }
  candidateHeadings.push("Unreleased");

  for (const heading of candidateHeadings) {
    const body = extractChangelogSection(changelogContent, heading);
    if (body) {
      return `${body}\n`;
    }
  }

  throw new Error(
    `Unable to find iOS changelog notes for ${version.canonicalVersion}. Add a matching section to ${IOS_CHANGELOG_FILE}.`,
  );
}
